fixes all failing tests on develop branch.
agco/elastic-harvesterjs pull request #89
Opened 2016-12-09 19:51 UTC by ShurakaiSoft

fixed all failing tests

2016-12-09 19:51 UTC, ssebro commented
This pull request is now managed with CodeReviewHub. <a href='https://github.com/agco/elastic-harvesterjs/pull/89'>Refresh</a>.<a href='#crh-update-none'></a>

2016-12-09 20:15 UTC, ShurakaiSoft commented
Weird, different tests failing with each test run...

2016-12-13 08:27 UTC, blabno requested changes
For me the tests are constantly failing. Especially the deletes.

2016-12-13 08:27 UTC, blabno commented on test/customRouting.spec.js
> +        return Promise.all(_.forEach(config.harvester.options.es_types, function (indexName) {
Promise.map is shorter.

2016-12-13 08:27 UTC, blabno commented on test/global.spec.js
> +// beforeEach(function () {
I think that we can revert all changes on this file.

2016-12-13 08:37 UTC, blabno commented
"deletes Should correctly sync primary resource deletes" and 
"deletes Should correctly sync resources with invalid data graphs" are failing for me.

2016-12-13 14:52 UTC, merged