Feature/lightweight adapter cache
agco/elastic-harvesterjs pull request #90
Opened 2016-12-12 19:16 UTC by ShurakaiSoft

2016-12-12 19:16 UTC, ssebro commented
This pull request is now managed with CodeReviewHub. <a href='https://github.com/agco/elastic-harvesterjs/pull/90'>Refresh</a>.<a href='#crh-update-none'></a>

2016-12-13 08:38 UTC, blabno requested changes
Tests for "deletes" are failing for me.

2016-12-13 14:03 UTC, ssebro commented on lib/singletonAdapterCache.js
> +        if (_singletonCache) return console.warn('Cache instance already created. You should probably use getInstance() to access it');
Not a nitpick, but a little surprised that initCache doesn't return a cache. Usually I think there's just the getInstance method, and it will check to see if it needs to initCache and automatically does it, then returns the instance, or if the cache already exists, it returns it. Should simplify a bit of this.

2016-12-13 15:46 UTC, ShurakaiSoft commented on lib/singletonAdapterCache.js
> +        if (_singletonCache) return console.warn('Cache instance already created. You should probably use getInstance() to access it');
The issue comes when you initCache a second time with a different adapter. Do you return the instance of the first adapter and ignore the user's request. Or do you change the instance to the new adapter and destroy the integrity of the first getInstance request.  Singletons are best when the take no arguments but in our case we need an adapter. So we need a way to setup the singleton with an adapter, and another way to get the instance.

2016-12-13 18:36 UTC, merged